Repository P4-Games/NoF-Smart-Contracts, pull requests merged in 2023-12, with the labels that each got.

#63 Feature/code improvements
  README.md
  commitlint.config.js
  contracts/testDai/TestDAI.v1.sol
  hardhat.config.ts
  package-lock.json
  package.json
Labels: enhancement

#64 Deploy #20231202
  README.md
  commitlint.config.js
  contracts/testDai/TestDAI.v1.sol
  hardhat.config.ts
  package-lock.json
  package.json
Labels: enhancement

#69 Feature/upgradeable contracts
  contracts/_deprecated/Alpha.v2__
  contracts/_deprecated/GammaCards.v4__
  contracts/_deprecated/GammaOffers.v3__
  contracts/_deprecated/GammaPacks.v2__
  contracts/_deprecated/TestDAI.v1__
  contracts/_deprecated/TestDAI.v2__
  contracts/alpha/Alpha.v3.sol
  contracts/alpha/ContextMixin.v2.sol
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  contracts/gamma/GammaPacks.v3.sol
  contracts/testDai/TestDAI.v3.sol
  hardhat.config.ts
  package-lock.json
  package.json
  scripts/deploy-mock-data.ts
  scripts/deploy.ts
Labels: enhancement

#73 Fix/require ownly owners
  contracts/gamma/GammaCards.v5.sol
Labels: enhancement

#78 Feature/open and transfer packs
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaPacks.v3.sol
  test/gamma.cards.test.ts
  test/gamma.packs.test.ts
Labels: enhancement

#79 [fix] :ambulance: update delete user offers
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  test/gamma.cards.test.ts
Labels: bug

#80 [ci] :green_heart: update contract names in env variables
  example_env
  scripts/common.ts
  scripts/mint-dais.ts
  test/common.ts
Labels: bug

#82 Feature/open packs cards
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaPacks.v3.sol
  package-lock.json
  package.json
  test/common.ts
  test/gamma.offers.test.ts
Labels: enhancement

#83 [chore] :wrench: update mumbai addresses
  README.md
Labels: enhancement

#84 [chore] :hammer: update dev script
  scripts/testAddCards.ts
Labels: enhancement

#85 Deploy-20231212
  README.md
  contracts/_deprecated/Alpha.v2__
  contracts/_deprecated/GammaCards.v4__
  contracts/_deprecated/GammaOffers.v3__
  contracts/_deprecated/GammaPacks.v2__
  contracts/_deprecated/TestDAI.v1__
  contracts/_deprecated/TestDAI.v2__
  contracts/alpha/Alpha.v3.sol
  contracts/alpha/ContextMixin.v2.sol
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  contracts/gamma/GammaPacks.v3.sol
  contracts/testDai/TestDAI.v3.sol
  example_env
  hardhat.config.ts
  package-lock.json
  package.json
  scripts/common.ts
  scripts/deploy-mock-data.ts
  scripts/deploy.ts
  scripts/mint-dais.ts
  scripts/testAddCards.ts
  test/common.ts
  test/gamma.cards.test.ts
  test/gamma.offers.test.ts
  test/gamma.packs.test.ts
Labels: bug, enhancement

#87 [ci] :construction_worker: avoid push on tests error
  .github/workflows/test.yaml
Labels: enhancement

#88 [ci] :wastebasket: update to fail
  test/alpha.test.ts
Labels: enhancement

#89 Feature/GitHub action on fail test
  .github/workflows/test.yaml
  test/alpha.test.ts
Labels: enhancement

#90 Features/exchange for any card
  contracts/gamma/GammaOffers.v4.sol
  test/gamma.offers.test.ts
Labels: enhancement

#97 Fix/contracts validations 20231223
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  contracts/gamma/GammaPacks.v3.sol
Labels: enhancement

#103 [feat] :necktie: add validation in buy packs (#101)
  contracts/gamma/GammaPacks.v3.sol
Labels: enhancement

#105 Feature/contracts logic and refactor
  contracts/alpha/Alpha.v3.sol
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  contracts/gamma/GammaPacks.v3.sol
  contracts/gamma/GammaTickets.v1.sol
  contracts/gamma/StringUtils.sol
  scripts/common.ts
  scripts/deploy-mock-data.ts
  test/alpha.test.ts
  test/common.ts
  test/gamma.cards.test.ts
  test/gamma.offers.test.ts
  test/gamma.packs.test.ts
  test/gamma.tickets.test.ts
Labels: enhancement

#107 Feature/106 contracts size
  README.md
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  contracts/gamma/GammaPacks.v3.sol
  contracts/gamma/GammaTickets.v1.sol
  contracts/gamma/libs/LibControlMgmt.sol
  contracts/gamma/libs/LibPackVerifier.sol
  contracts/gamma/libs/LibStringUtils.sol
  example_env
  scripts/common.ts
  scripts/deploy-mock-data.ts
  test/common.ts
  test/gamma.cards.test.ts
Labels: documentation, enhancement

#110 [fix] :bug: fix pay burn-prize enter condition (#2)
  contracts/gamma/GammaCards.v5.sol
Labels: bug

#111 [fix] :fire: remove invalid validation (#2)
  contracts/gamma/GammaCards.v5.sol
Labels: bug

#113 [feat] :necktie: update secondary prize value (#112)
  contracts/gamma/GammaCards.v5.sol
Labels: enhancement

#114 [feat] :rewind: restore 1 DAI value for secondary album prize (#112)
  contracts/gamma/GammaCards.v5.sol
Labels: enhancement

#116 [feat] :safety_vest: check if user has enough copies to burn with off…
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaOffers.v4.sol
  test/gamma.cards.test.ts
Labels: enhancement

#117 [fix] :adhesive_bandage: corrected user address in buy packs
  contracts/_deprecated/Alpha.v2__
  contracts/_deprecated/GammaCards.v4__
  contracts/_deprecated/GammaOffers.v3__
  contracts/_deprecated/GammaPacks.v2__
  contracts/_deprecated/TestDAI.v1__
  contracts/_deprecated/TestDAI.v2__
  contracts/gamma/GammaCards.v5.sol
  contracts/gamma/GammaCardsNFT.v1.sol
  contracts/gamma/GammaOffers.v4.sol
  contracts/gamma/GammaPacks.v3.sol
  contracts/gamma/GammaTickets.v1.sol
Labels: bug

#118 [refactor] :recycle: reduce gamma cards contract size (#106)
  contracts/gamma/GammaCards.v5.sol
  test/common.ts
  test/gamma.cards.test.ts
Labels: bug
